# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 12:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20160422_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
